module.exports = {
  "SESSION_ID": "ALYA-34feb9ee66fc53a04964ba3a2823b7f0e86d4e05",
  "PREFIX": ".",
  "BOT_NAME": "QUEEN_ALYA",
  "OWNER_NAME": "KING",
  "MODE": "private",
  "OWNER_NUMBER": "2349123721026",
  "PM_BLOCKER": "true",
  "DELETE": "false",
  "ANTILINK": "false",
  "ANTILINK_ACTION": "warn",
  "ANTIBOT": "false",
  "ANTIBOT_ACTION": "kick",
  "ANTIWORD_MODE": "false",
  "ANTIWORD_ACTION": "warn",
  "ANTI_CALL": "true",
  "ANTI_CALL_MESSAGE": "My owner is busy rn",
  "ANTIWORD": "fek",
  "GREETING": "false",
  "MENUTYPE": "v2",
  "LINK_DELETE": "true",
  "AFK": "false",
  "AFK_REASON": "",
  "AUTO_STATUS": "true",
  "AUTO_STATUS_EMOJI": "👑",
  "CHAT_BOT": "false",
  "AUTO_SAVE_STATUS": "true",
  "SAVE_STATUS_FROM": "2348100835767,2346277893334"
};